refactor: migrating from class to functional components
felquis/react-credit-cards-2 pull request #4
Opened 2022-10-10 19:10 UTC by SeanCassiere

closes #3

2022-10-10 19:19 UTC, SeanCassiere commented on package.json
> -    "eslint-plugin-react-hooks": "^4.3.0",
this should be dev dependancy

2022-10-10 19:23 UTC, SeanCassiere commented on package.json
> -    "eslint-plugin-react-hooks": "^4.3.0",
nevermind, it turns out I've moved it to dev dependencies and this was an artifact of a deleted branch

2022-10-14 12:07 UTC, felquis requested changes
Looking good, great work.

2022-10-14 12:07 UTC, felquis commented on README.md
> +          type="tel"
should be `type="number"`

2022-10-14 12:19 UTC, SeanCassiere commented on README.md
> +          type="tel"
fixed

2022-10-14 12:21 UTC, felquis approved these changes

2022-10-14 12:22 UTC, merged